# Generated by Django 5.2 on 2025-05-05 21:19

import prd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd',
            name='ai_processing_status',
            field=models.CharField(default='not_started', max_length=50),
        ),
        migrations.AddField(
            model_name='prd',
            name='combined_knowledge_base',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prd',
            name='reference_data_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='analysis_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=prd.models.reference_file_path),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('url', 'External URL'), ('text', 'Text Input')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='prd',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prd',
            name='project_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectreference',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectreference',
            name='content_type',
            field=models.CharField(choices=[('meeting_notes', 'Meeting Notes'), ('requirement_doc', 'Requirement Document'), ('sample_app', 'Sample App'), ('similar_app', 'Similar App'), ('website', 'Website'), ('article', 'Article'), ('api_doc', 'API Documentation'), ('design_doc', 'Design Document'), ('user_feedback', 'User Feedback'), ('market_research', 'Market Research'), ('other', 'Other')], max_length=50),
        ),
    ]
